name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Zip the application
      run: zip -r application.zip . -x '*.git*'

    - name: Upload zip to S3
      uses: actions/aws/cli@master
      with:
        region: us-west-2
        script: "aws s3 cp application.zip s3://your-s3-bucket/${{ github.sha }}/application.zip"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy to Elastic Beanstalk
      env:
        SECRET_VALUE: ${{ secrets.SECRET_VALUE }}
      run: |
        aws elasticbeanstalk create-application-version --application-name hello-world-app --version-label ${{ github.sha }} --source-bundle S3Bucket="your-s3-bucket",S3Key="${{ github.sha }}/application.zip"
        aws elasticbeanstalk update-environment --application-name hello-world-app --environment-name your-env-name --version-label ${{ github.sha }}
