name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Zip the application
      run: zip -r application.zip . -x '*.git*'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload ZIP to S3
      run: |
        aws s3 cp application.zip s3://sofit-task-bucket/${{ github.sha }}/application.zip

    - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version --application-name OsamaTesting --version-label ${{ github.sha }} --source-bundle S3Bucket="sofit-task-bucket",S3Key="${{ github.sha }}/application.zip"
        aws elasticbeanstalk update-environment --application-name OsamaTesting --environment-name OsamaTesting-env --version-label ${{ github.sha }}
